name: bison
recipe: laravel
config:
  composer_version: '2-latest'
  webroot: ./public
  database: mysql:8.0
  php: '8.3'
  via: nginx
  cache: redis
services:
  appserver:
    run:
      - composer install --optimize-autoloader
tooling:
  dust:
    service: appserver
    description: Run Duster fix|lint
    cmd: ./vendor/bin/duster
    dir: /app
  art:
    service: appserver
    description: Run an Artisan command
    cmd: php artisan
    dir: /app
