name: bison
recipe: laravel
config:
  composer_version: '2-latest'
  webroot: ./public
  database: mysql:8.0
  php: '8.3'
  via: nginx
  cache: redis
services:
  appserver:
    ssl: true
    sslExpose: true
  node:
    type: node:22
events:
  pre-start:
    - appserver: |
        composer run post-root-package-install
        composer install
  post-start:
    - appserver: |
        php artisan key:generate --ansi
        php artisan migrate
    - node: npm install && npm run build
tooling:
  npm:
    service: node
  dust:
    service: appserver
    description: Run Duster fix|lint
    cmd: ./vendor/bin/duster
    dir: /app
  art:
    service: appserver
    description: Run an Artisan command
    cmd: php artisan
    dir: /app
  test:
    service: appserver
    description: Run Pest
    cmd: |
      php artisan migrate --env=testing
      ./vendor/bin/pest
  cache:
    service: appserver
    description: Cache all the things
    cmd: |
      php artisan config:cache
      php artisan event:cache
      php artisan route:cache
      php artisan view:cache
      php artisan icons:cache
      php artisan optimize
      php artisan filament:optimize
      php artisan filament:cache-components
  clear:
    service: appserver
    description: Clear all caches
    cmd: |
      php artisan cache:clear
      php artisan config:clear
      php artisan event:clear
      php artisan route:clear
      php artisan view:clear
      php artisan filament:optimize-clear
      php artisan filament:clear-cached-components
